version: "3.8"

services:
  backend:
    build: ./
    # for prod: npm run start
    command: npm run dev
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - memory-game
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.5-bionic
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - memory-game

networks:
  memory-game:
    driver: bridge

volumes:
  mongo-data:
